/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type StudentStatus = typeof StudentStatus[keyof typeof StudentStatus];


export const StudentStatus = {
  active: 'active',
  inactive: 'inactive',
  graduated: 'graduated',
} as const;

export interface Student {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  course: string;
  year: number;
  status: StudentStatus;
  enrollmentDate: string;
  createdAt: string;
  updatedAt: string;
}

export interface StudentInput {
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  /** @minLength 1 */
  course: string;
  /**
     * @minimum 1
     * @maximum 6
     */
  year: number;
  status: StudentStatus;
  enrollmentDate: string;
}

export interface StudentUpdate {
  /** @minLength 1 */
  firstName?: string;
  /** @minLength 1 */
  lastName?: string;
  email?: string;
  /** @nullable */
  phone?: string | null;
  /** @minLength 1 */
  course?: string;
  /**
     * @minimum 1
     * @maximum 6
     */
  year?: number;
  status?: StudentStatus;
  enrollmentDate?: string;
}

export interface CourseCount {
  course: string;
  count: number;
}

export interface StudentSummary {
  total: number;
  active: number;
  inactive: number;
  graduated: number;
  courses: CourseCount[];
}

export interface ErrorResponse {
  error: string;
}

export type ListStudentsParams = {
search?: string;
course?: string;
status?: StudentStatus;
/**
 * @minimum 1
 * @maximum 6
 */
year?: number;
};

export type GetRecentStudentsParams = {
/**
 * @minimum 1
 * @maximum 10
 */
limit?: number;
};

